oc_platform_home:
    path: /platform
    defaults: { _controller: OCPlatformBundle:Advert:index }

oc_platform_view:
    path: /platform/advert/{id}
    defaults: { _controller: OCPlatformBundle:Advert:view }

oc_platform_add:
    path: /add
    defaults: { _controller: OCPlatformBundle:Advert:add }